// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// row_logprod_mask_idx_slice
Rcpp::NumericVector row_logprod_mask_idx_slice(const Rcpp::IntegerMatrix& curr_inter, const Rcpp::IntegerMatrix& focus_st, const Rcpp::IntegerVector& i_idx, const Rcpp::IntegerVector& j_idx, const Rcpp::NumericMatrix& log1m_pipj);
RcppExport SEXP _COILplus_row_logprod_mask_idx_slice(SEXP curr_interSEXP, SEXP focus_stSEXP, SEXP i_idxSEXP, SEXP j_idxSEXP, SEXP log1m_pipjSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type curr_inter(curr_interSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type focus_st(focus_stSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type i_idx(i_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type j_idx(j_idxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type log1m_pipj(log1m_pipjSEXP);
    rcpp_result_gen = Rcpp::wrap(row_logprod_mask_idx_slice(curr_inter, focus_st, i_idx, j_idx, log1m_pipj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_COILplus_row_logprod_mask_idx_slice", (DL_FUNC) &_COILplus_row_logprod_mask_idx_slice, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_COILplus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
