# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

row_logprod_mask_idx_slice <- function(curr_inter, focus_st, i_idx, j_idx, log1m_pipj) {
    .Call(`_COILplus_row_logprod_mask_idx_slice`, curr_inter, focus_st, i_idx, j_idx, log1m_pipj)
}

